/* Generated by DBCC, see <https://github.com/howerj/dbcc> */
#include "test.h"
#include <inttypes.h>
#include <assert.h>

#define UNUSED(X) ((void)(X))

static inline uint64_t reverse_byte_order(uint64_t x) {
	x = (x & 0x00000000FFFFFFFF) << 32 | (x & 0xFFFFFFFF00000000) >> 32;
	x = (x & 0x0000FFFF0000FFFF) << 16 | (x & 0xFFFF0000FFFF0000) >> 16;
	x = (x & 0x00FF00FF00FF00FF) << 8  | (x & 0xFF00FF00FF00FF00) >> 8;
	return x;
}

static inline int print_helper(int r, int print_return_value) {
	return ((r >= 0) && (print_return_value >= 0)) ? r + print_return_value : -1;
}

static int pack_can_0x300_ME1_1(can_obj_test_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* RPM: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x300_ME1_1.RPM)) & 0xffff;
	i |= x;
	/* TPS: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x300_ME1_1.TPS)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* MAP: start-bit 32, length 16, endianess intel, scaling 0.01, offset 0 */
	x = ((uint16_t)(o->can_0x300_ME1_1.MAP)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* IAT: start-bit 48, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x300_ME1_1.IAT)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x300_ME1_1_tx = 1;
	return 0;
}

static int unpack_can_0x300_ME1_1(can_obj_test_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* RPM: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = i & 0xffff;
	o->can_0x300_ME1_1.RPM = x;
	/* TPS: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x300_ME1_1.TPS = x;
	/* MAP: start-bit 32, length 16, endianess intel, scaling 0.01, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x300_ME1_1.MAP = x;
	/* IAT: start-bit 48, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->can_0x300_ME1_1.IAT = x;
	o->can_0x300_ME1_1_rx = 1;
	o->can_0x300_ME1_1_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x300_RPM(const can_obj_test_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x300_ME1_1.RPM);
	*out = rval;
	return 0;
}

int encode_can_0x300_RPM(can_obj_test_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x300_ME1_1.RPM = in;
	return 0;
}

int decode_can_0x300_TPS(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x300_ME1_1.TPS);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x300_TPS(can_obj_test_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x300_ME1_1.TPS = in;
	return 0;
}

int decode_can_0x300_MAP(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x300_ME1_1.MAP);
	rval *= 0.01;
	*out = rval;
	return 0;
}

int encode_can_0x300_MAP(can_obj_test_h_t *o, double in) {
	assert(o);
	in *= 100;
	o->can_0x300_ME1_1.MAP = in;
	return 0;
}

int decode_can_0x300_IAT(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x300_ME1_1.IAT);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x300_IAT(can_obj_test_h_t *o, double in) {
	assert(o);
	o->can_0x300_ME1_1.IAT = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->can_0x300_ME1_1.IAT = in;
	return 0;
}

int print_can_0x300_ME1_1(const can_obj_test_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "RPM = (wire: %.0f)\n", (double)(o->can_0x300_ME1_1.RPM)));
	r = print_helper(r, fprintf(output, "TPS = (wire: %.0f)\n", (double)(o->can_0x300_ME1_1.TPS)));
	r = print_helper(r, fprintf(output, "MAP = (wire: %.0f)\n", (double)(o->can_0x300_ME1_1.MAP)));
	r = print_helper(r, fprintf(output, "IAT = (wire: %.0f)\n", (double)(o->can_0x300_ME1_1.IAT)));
	return r;
}

static int pack_can_0x301_ME1_2(can_obj_test_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* RPM_HardLimit: start-bit 0, length 16, endianess intel, scaling 0.4, offset 0 */
	x = ((uint16_t)(o->can_0x301_ME1_2.RPM_HardLimit)) & 0xffff;
	i |= x;
	/* Lambda_Trim: start-bit 32, length 16, endianess intel, scaling 0.01, offset 0 */
	x = ((uint16_t)(o->can_0x301_ME1_2.Lambda_Trim)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* AFRCurr_1: start-bit 16, length 8, endianess intel, scaling 0.05, offset 7.5 */
	x = ((uint8_t)(o->can_0x301_ME1_2.AFRCurr_1)) & 0xff;
	x <<= 16; 
	i |= x;
	/* AFRCurr_2: start-bit 24, length 8, endianess intel, scaling 0.05, offset 7.5 */
	x = ((uint8_t)(o->can_0x301_ME1_2.AFRCurr_2)) & 0xff;
	x <<= 24; 
	i |= x;
	/* AFR_Target: start-bit 48, length 8, endianess intel, scaling 0.05, offset 7.5 */
	x = ((uint8_t)(o->can_0x301_ME1_2.AFR_Target)) & 0xff;
	x <<= 48; 
	i |= x;
	/* Fuel_Eth_Perc: start-bit 56, length 8, endianess intel, scaling 0.5, offset 0 */
	x = ((uint8_t)(o->can_0x301_ME1_2.Fuel_Eth_Perc)) & 0xff;
	x <<= 56; 
	i |= x;
	*data = (i);
	o->can_0x301_ME1_2_tx = 1;
	return 0;
}

static int unpack_can_0x301_ME1_2(can_obj_test_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* RPM_HardLimit: start-bit 0, length 16, endianess intel, scaling 0.4, offset 0 */
	x = i & 0xffff;
	o->can_0x301_ME1_2.RPM_HardLimit = x;
	/* Lambda_Trim: start-bit 32, length 16, endianess intel, scaling 0.01, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x301_ME1_2.Lambda_Trim = x;
	/* AFRCurr_1: start-bit 16, length 8, endianess intel, scaling 0.05, offset 7.5 */
	x = (i >> 16) & 0xff;
	o->can_0x301_ME1_2.AFRCurr_1 = x;
	/* AFRCurr_2: start-bit 24, length 8, endianess intel, scaling 0.05, offset 7.5 */
	x = (i >> 24) & 0xff;
	o->can_0x301_ME1_2.AFRCurr_2 = x;
	/* AFR_Target: start-bit 48, length 8, endianess intel, scaling 0.05, offset 7.5 */
	x = (i >> 48) & 0xff;
	o->can_0x301_ME1_2.AFR_Target = x;
	/* Fuel_Eth_Perc: start-bit 56, length 8, endianess intel, scaling 0.5, offset 0 */
	x = (i >> 56) & 0xff;
	o->can_0x301_ME1_2.Fuel_Eth_Perc = x;
	o->can_0x301_ME1_2_rx = 1;
	o->can_0x301_ME1_2_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x301_RPM_HardLimit(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x301_ME1_2.RPM_HardLimit);
	rval *= 0.4;
	if (rval <= 26214) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x301_RPM_HardLimit(can_obj_test_h_t *o, double in) {
	assert(o);
	o->can_0x301_ME1_2.RPM_HardLimit = 0;
	if (in > 26214)
		return -1;
	in *= 2.5;
	o->can_0x301_ME1_2.RPM_HardLimit = in;
	return 0;
}

int decode_can_0x301_Lambda_Trim(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x301_ME1_2.Lambda_Trim);
	rval *= 0.01;
	*out = rval;
	return 0;
}

int encode_can_0x301_Lambda_Trim(can_obj_test_h_t *o, double in) {
	assert(o);
	in *= 100;
	o->can_0x301_ME1_2.Lambda_Trim = in;
	return 0;
}

int decode_can_0x301_AFRCurr_1(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x301_ME1_2.AFRCurr_1);
	rval *= 0.05;
	rval += 7.5;
	if ((rval >= 7.5) && (rval <= 20.25)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x301_AFRCurr_1(can_obj_test_h_t *o, double in) {
	assert(o);
	o->can_0x301_ME1_2.AFRCurr_1 = 0;
	if (in < 7.5)
		return -1;
	if (in > 20.25)
		return -1;
	in += -7.5;
	in *= 20;
	o->can_0x301_ME1_2.AFRCurr_1 = in;
	return 0;
}

int decode_can_0x301_AFRCurr_2(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x301_ME1_2.AFRCurr_2);
	rval *= 0.05;
	rval += 7.5;
	if ((rval >= 7.5) && (rval <= 20.25)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x301_AFRCurr_2(can_obj_test_h_t *o, double in) {
	assert(o);
	o->can_0x301_ME1_2.AFRCurr_2 = 0;
	if (in < 7.5)
		return -1;
	if (in > 20.25)
		return -1;
	in += -7.5;
	in *= 20;
	o->can_0x301_ME1_2.AFRCurr_2 = in;
	return 0;
}

int decode_can_0x301_AFR_Target(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x301_ME1_2.AFR_Target);
	rval *= 0.05;
	rval += 7.5;
	if ((rval >= 7.5) && (rval <= 20.25)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x301_AFR_Target(can_obj_test_h_t *o, double in) {
	assert(o);
	o->can_0x301_ME1_2.AFR_Target = 0;
	if (in < 7.5)
		return -1;
	if (in > 20.25)
		return -1;
	in += -7.5;
	in *= 20;
	o->can_0x301_ME1_2.AFR_Target = in;
	return 0;
}

int decode_can_0x301_Fuel_Eth_Perc(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x301_ME1_2.Fuel_Eth_Perc);
	rval *= 0.5;
	if (rval <= 127.5) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x301_Fuel_Eth_Perc(can_obj_test_h_t *o, double in) {
	assert(o);
	o->can_0x301_ME1_2.Fuel_Eth_Perc = 0;
	if (in > 127.5)
		return -1;
	in *= 2;
	o->can_0x301_ME1_2.Fuel_Eth_Perc = in;
	return 0;
}

int print_can_0x301_ME1_2(const can_obj_test_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "RPM_HardLimit = (wire: %.0f)\n", (double)(o->can_0x301_ME1_2.RPM_HardLimit)));
	r = print_helper(r, fprintf(output, "Lambda_Trim = (wire: %.0f)\n", (double)(o->can_0x301_ME1_2.Lambda_Trim)));
	r = print_helper(r, fprintf(output, "AFRCurr_1 = (wire: %.0f)\n", (double)(o->can_0x301_ME1_2.AFRCurr_1)));
	r = print_helper(r, fprintf(output, "AFRCurr_2 = (wire: %.0f)\n", (double)(o->can_0x301_ME1_2.AFRCurr_2)));
	r = print_helper(r, fprintf(output, "AFR_Target = (wire: %.0f)\n", (double)(o->can_0x301_ME1_2.AFR_Target)));
	r = print_helper(r, fprintf(output, "Fuel_Eth_Perc = (wire: %.0f)\n", (double)(o->can_0x301_ME1_2.Fuel_Eth_Perc)));
	return r;
}

static int pack_can_0x302_ME1_3(can_obj_test_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* IgnAdvAngle: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x302_ME1_3.IgnAdvAngle)) & 0xffff;
	i |= x;
	/* IgnDwell: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x302_ME1_3.IgnDwell)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* Pri_InjAngle: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x302_ME1_3.Pri_InjAngle)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* Pri_InjPw: start-bit 48, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x302_ME1_3.Pri_InjPw)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x302_ME1_3_tx = 1;
	return 0;
}

static int unpack_can_0x302_ME1_3(can_obj_test_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* IgnAdvAngle: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->can_0x302_ME1_3.IgnAdvAngle = x;
	/* IgnDwell: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x302_ME1_3.IgnDwell = x;
	/* Pri_InjAngle: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x302_ME1_3.Pri_InjAngle = x;
	/* Pri_InjPw: start-bit 48, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->can_0x302_ME1_3.Pri_InjPw = x;
	o->can_0x302_ME1_3_rx = 1;
	o->can_0x302_ME1_3_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x302_IgnAdvAngle(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x302_ME1_3.IgnAdvAngle);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x302_IgnAdvAngle(can_obj_test_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x302_ME1_3.IgnAdvAngle = in;
	return 0;
}

int decode_can_0x302_IgnDwell(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x302_ME1_3.IgnDwell);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x302_IgnDwell(can_obj_test_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x302_ME1_3.IgnDwell = in;
	return 0;
}

int decode_can_0x302_Pri_InjAngle(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x302_ME1_3.Pri_InjAngle);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x302_Pri_InjAngle(can_obj_test_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x302_ME1_3.Pri_InjAngle = in;
	return 0;
}

int decode_can_0x302_Pri_InjPw(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x302_ME1_3.Pri_InjPw);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x302_Pri_InjPw(can_obj_test_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x302_ME1_3.Pri_InjPw = in;
	return 0;
}

int print_can_0x302_ME1_3(const can_obj_test_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "IgnAdvAngle = (wire: %.0f)\n", (double)(o->can_0x302_ME1_3.IgnAdvAngle)));
	r = print_helper(r, fprintf(output, "IgnDwell = (wire: %.0f)\n", (double)(o->can_0x302_ME1_3.IgnDwell)));
	r = print_helper(r, fprintf(output, "Pri_InjAngle = (wire: %.0f)\n", (double)(o->can_0x302_ME1_3.Pri_InjAngle)));
	r = print_helper(r, fprintf(output, "Pri_InjPw = (wire: %.0f)\n", (double)(o->can_0x302_ME1_3.Pri_InjPw)));
	return r;
}

static int pack_can_0x303_ME1_4(can_obj_test_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* Sec_InjAngle: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x303_ME1_4.Sec_InjAngle)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* Sec_InjPw: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x303_ME1_4.Sec_InjPw)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* Pri_InjDuty: start-bit 0, length 8, endianess intel, scaling 0.5, offset 0 */
	x = ((uint8_t)(o->can_0x303_ME1_4.Pri_InjDuty)) & 0xff;
	i |= x;
	/* Sec_InjDuty: start-bit 8, length 8, endianess intel, scaling 0.5, offset 0 */
	x = ((uint8_t)(o->can_0x303_ME1_4.Sec_InjDuty)) & 0xff;
	x <<= 8; 
	i |= x;
	/* Boost_Ctrl_Duty: start-bit 48, length 8, endianess intel, scaling 0.5, offset 0 */
	x = ((uint8_t)(o->can_0x303_ME1_4.Boost_Ctrl_Duty)) & 0xff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x303_ME1_4_tx = 1;
	return 0;
}

static int unpack_can_0x303_ME1_4(can_obj_test_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* Sec_InjAngle: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x303_ME1_4.Sec_InjAngle = x;
	/* Sec_InjPw: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x303_ME1_4.Sec_InjPw = x;
	/* Pri_InjDuty: start-bit 0, length 8, endianess intel, scaling 0.5, offset 0 */
	x = i & 0xff;
	o->can_0x303_ME1_4.Pri_InjDuty = x;
	/* Sec_InjDuty: start-bit 8, length 8, endianess intel, scaling 0.5, offset 0 */
	x = (i >> 8) & 0xff;
	o->can_0x303_ME1_4.Sec_InjDuty = x;
	/* Boost_Ctrl_Duty: start-bit 48, length 8, endianess intel, scaling 0.5, offset 0 */
	x = (i >> 48) & 0xff;
	o->can_0x303_ME1_4.Boost_Ctrl_Duty = x;
	o->can_0x303_ME1_4_rx = 1;
	o->can_0x303_ME1_4_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x303_Sec_InjAngle(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x303_ME1_4.Sec_InjAngle);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x303_Sec_InjAngle(can_obj_test_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x303_ME1_4.Sec_InjAngle = in;
	return 0;
}

int decode_can_0x303_Sec_InjPw(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x303_ME1_4.Sec_InjPw);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x303_Sec_InjPw(can_obj_test_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x303_ME1_4.Sec_InjPw = in;
	return 0;
}

int decode_can_0x303_Pri_InjDuty(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x303_ME1_4.Pri_InjDuty);
	rval *= 0.5;
	if (rval <= 127.5) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x303_Pri_InjDuty(can_obj_test_h_t *o, double in) {
	assert(o);
	o->can_0x303_ME1_4.Pri_InjDuty = 0;
	if (in > 127.5)
		return -1;
	in *= 2;
	o->can_0x303_ME1_4.Pri_InjDuty = in;
	return 0;
}

int decode_can_0x303_Sec_InjDuty(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x303_ME1_4.Sec_InjDuty);
	rval *= 0.5;
	if (rval <= 127.5) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x303_Sec_InjDuty(can_obj_test_h_t *o, double in) {
	assert(o);
	o->can_0x303_ME1_4.Sec_InjDuty = 0;
	if (in > 127.5)
		return -1;
	in *= 2;
	o->can_0x303_ME1_4.Sec_InjDuty = in;
	return 0;
}

int decode_can_0x303_Boost_Ctrl_Duty(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x303_ME1_4.Boost_Ctrl_Duty);
	rval *= 0.5;
	if (rval <= 127.5) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x303_Boost_Ctrl_Duty(can_obj_test_h_t *o, double in) {
	assert(o);
	o->can_0x303_ME1_4.Boost_Ctrl_Duty = 0;
	if (in > 127.5)
		return -1;
	in *= 2;
	o->can_0x303_ME1_4.Boost_Ctrl_Duty = in;
	return 0;
}

int print_can_0x303_ME1_4(const can_obj_test_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "Sec_InjAngle = (wire: %.0f)\n", (double)(o->can_0x303_ME1_4.Sec_InjAngle)));
	r = print_helper(r, fprintf(output, "Sec_InjPw = (wire: %.0f)\n", (double)(o->can_0x303_ME1_4.Sec_InjPw)));
	r = print_helper(r, fprintf(output, "Pri_InjDuty = (wire: %.0f)\n", (double)(o->can_0x303_ME1_4.Pri_InjDuty)));
	r = print_helper(r, fprintf(output, "Sec_InjDuty = (wire: %.0f)\n", (double)(o->can_0x303_ME1_4.Sec_InjDuty)));
	r = print_helper(r, fprintf(output, "Boost_Ctrl_Duty = (wire: %.0f)\n", (double)(o->can_0x303_ME1_4.Boost_Ctrl_Duty)));
	return r;
}

static int pack_can_0x304_ME1_5(can_obj_test_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* Oil_T: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x304_ME1_5.Oil_T)) & 0xffff;
	i |= x;
	/* Oil_P: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x304_ME1_5.Oil_P)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* CLT: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x304_ME1_5.CLT)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* VBAT: start-bit 48, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x304_ME1_5.VBAT)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	o->can_0x304_ME1_5_tx = 1;
	return 0;
}

static int unpack_can_0x304_ME1_5(can_obj_test_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* Oil_T: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->can_0x304_ME1_5.Oil_T = x;
	/* Oil_P: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x304_ME1_5.Oil_P = x;
	/* CLT: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x304_ME1_5.CLT = x;
	/* VBAT: start-bit 48, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->can_0x304_ME1_5.VBAT = x;
	o->can_0x304_ME1_5_rx = 1;
	o->can_0x304_ME1_5_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x304_Oil_T(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x304_ME1_5.Oil_T);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x304_Oil_T(can_obj_test_h_t *o, double in) {
	assert(o);
	o->can_0x304_ME1_5.Oil_T = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->can_0x304_ME1_5.Oil_T = in;
	return 0;
}

int decode_can_0x304_Oil_P(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x304_ME1_5.Oil_P);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x304_Oil_P(can_obj_test_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x304_ME1_5.Oil_P = in;
	return 0;
}

int decode_can_0x304_CLT(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x304_ME1_5.CLT);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x304_CLT(can_obj_test_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x304_ME1_5.CLT = in;
	return 0;
}

int decode_can_0x304_VBAT(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x304_ME1_5.VBAT);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x304_VBAT(can_obj_test_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x304_ME1_5.VBAT = in;
	return 0;
}

int print_can_0x304_ME1_5(const can_obj_test_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "Oil_T = (wire: %.0f)\n", (double)(o->can_0x304_ME1_5.Oil_T)));
	r = print_helper(r, fprintf(output, "Oil_P = (wire: %.0f)\n", (double)(o->can_0x304_ME1_5.Oil_P)));
	r = print_helper(r, fprintf(output, "CLT = (wire: %.0f)\n", (double)(o->can_0x304_ME1_5.CLT)));
	r = print_helper(r, fprintf(output, "VBAT = (wire: %.0f)\n", (double)(o->can_0x304_ME1_5.VBAT)));
	return r;
}

static int pack_can_0x305_ME1_6(can_obj_test_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* MAP_Target: start-bit 8, length 16, endianess intel, scaling 0.01, offset 0 */
	x = ((uint16_t)(o->can_0x305_ME1_6.MAP_Target)) & 0xffff;
	x <<= 8; 
	i |= x;
	/* Vehicle_Speed: start-bit 24, length 16, endianess intel, scaling 0.008, offset 0 */
	x = ((uint16_t)(o->can_0x305_ME1_6.Vehicle_Speed)) & 0xffff;
	x <<= 24; 
	i |= x;
	/* EPS_Ev_Msk: start-bit 40, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x305_ME1_6.EPS_Ev_Msk)) & 0xffff;
	x <<= 40; 
	i |= x;
	/* Gear_Pos: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x305_ME1_6.Gear_Pos)) & 0xff;
	i |= x;
	*data = (i);
	o->can_0x305_ME1_6_tx = 1;
	return 0;
}

static int unpack_can_0x305_ME1_6(can_obj_test_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* MAP_Target: start-bit 8, length 16, endianess intel, scaling 0.01, offset 0 */
	x = (i >> 8) & 0xffff;
	o->can_0x305_ME1_6.MAP_Target = x;
	/* Vehicle_Speed: start-bit 24, length 16, endianess intel, scaling 0.008, offset 0 */
	x = (i >> 24) & 0xffff;
	o->can_0x305_ME1_6.Vehicle_Speed = x;
	/* EPS_Ev_Msk: start-bit 40, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 40) & 0xffff;
	o->can_0x305_ME1_6.EPS_Ev_Msk = x;
	/* Gear_Pos: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = i & 0xff;
	o->can_0x305_ME1_6.Gear_Pos = x;
	o->can_0x305_ME1_6_rx = 1;
	o->can_0x305_ME1_6_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x305_MAP_Target(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x305_ME1_6.MAP_Target);
	rval *= 0.01;
	if (rval <= 655.35) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x305_MAP_Target(can_obj_test_h_t *o, double in) {
	assert(o);
	o->can_0x305_ME1_6.MAP_Target = 0;
	if (in > 655.35)
		return -1;
	in *= 100;
	o->can_0x305_ME1_6.MAP_Target = in;
	return 0;
}

int decode_can_0x305_Vehicle_Speed(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x305_ME1_6.Vehicle_Speed);
	rval *= 0.008;
	if (rval <= 524.28) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x305_Vehicle_Speed(can_obj_test_h_t *o, double in) {
	assert(o);
	o->can_0x305_ME1_6.Vehicle_Speed = 0;
	if (in > 524.28)
		return -1;
	in *= 125;
	o->can_0x305_ME1_6.Vehicle_Speed = in;
	return 0;
}

int decode_can_0x305_EPS_Ev_Msk(const can_obj_test_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x305_ME1_6.EPS_Ev_Msk);
	*out = rval;
	return 0;
}

int encode_can_0x305_EPS_Ev_Msk(can_obj_test_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x305_ME1_6.EPS_Ev_Msk = in;
	return 0;
}

int decode_can_0x305_Gear_Pos(const can_obj_test_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x305_ME1_6.Gear_Pos);
	*out = rval;
	return 0;
}

int encode_can_0x305_Gear_Pos(can_obj_test_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x305_ME1_6.Gear_Pos = in;
	return 0;
}

int print_can_0x305_ME1_6(const can_obj_test_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "MAP_Target = (wire: %.0f)\n", (double)(o->can_0x305_ME1_6.MAP_Target)));
	r = print_helper(r, fprintf(output, "Vehicle_Speed = (wire: %.0f)\n", (double)(o->can_0x305_ME1_6.Vehicle_Speed)));
	r = print_helper(r, fprintf(output, "EPS_Ev_Msk = (wire: %.0f)\n", (double)(o->can_0x305_ME1_6.EPS_Ev_Msk)));
	r = print_helper(r, fprintf(output, "Gear_Pos = (wire: %.0f)\n", (double)(o->can_0x305_ME1_6.Gear_Pos)));
	return r;
}

static int pack_can_0x306_ME1_7(can_obj_test_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* Knock_Reading: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x306_ME1_7.Knock_Reading)) & 0xffff;
	i |= x;
	/* EGT_1: start-bit 40, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x306_ME1_7.EGT_1)) & 0xffff;
	x <<= 40; 
	i |= x;
	/* Knock_Ign_Adv_Mod: start-bit 16, length 8, endianess intel, scaling 0.1, offset 0 */
	x = ((uint8_t)(o->can_0x306_ME1_7.Knock_Ign_Adv_Mod)) & 0xff;
	x <<= 16; 
	i |= x;
	/* Fuel_Press: start-bit 24, length 8, endianess intel, scaling 5, offset 0 */
	x = ((uint8_t)(o->can_0x306_ME1_7.Fuel_Press)) & 0xff;
	x <<= 24; 
	i |= x;
	/* Fuel_Temp: start-bit 32, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8_t)(o->can_0x306_ME1_7.Fuel_Temp)) & 0xff;
	x <<= 32; 
	i |= x;
	*data = (i);
	o->can_0x306_ME1_7_tx = 1;
	return 0;
}

static int unpack_can_0x306_ME1_7(can_obj_test_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* Knock_Reading: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = i & 0xffff;
	o->can_0x306_ME1_7.Knock_Reading = x;
	/* EGT_1: start-bit 40, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 40) & 0xffff;
	o->can_0x306_ME1_7.EGT_1 = x;
	/* Knock_Ign_Adv_Mod: start-bit 16, length 8, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xff;
	o->can_0x306_ME1_7.Knock_Ign_Adv_Mod = x;
	/* Fuel_Press: start-bit 24, length 8, endianess intel, scaling 5, offset 0 */
	x = (i >> 24) & 0xff;
	o->can_0x306_ME1_7.Fuel_Press = x;
	/* Fuel_Temp: start-bit 32, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xff;
	o->can_0x306_ME1_7.Fuel_Temp = x;
	o->can_0x306_ME1_7_rx = 1;
	o->can_0x306_ME1_7_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x306_Knock_Reading(const can_obj_test_h_t *o, uint16_t *out) {
	assert(o);
	assert(out);
	uint16_t rval = (uint16_t)(o->can_0x306_ME1_7.Knock_Reading);
	*out = rval;
	return 0;
}

int encode_can_0x306_Knock_Reading(can_obj_test_h_t *o, uint16_t in) {
	assert(o);
	o->can_0x306_ME1_7.Knock_Reading = in;
	return 0;
}

int decode_can_0x306_EGT_1(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x306_ME1_7.EGT_1);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x306_EGT_1(can_obj_test_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x306_ME1_7.EGT_1 = in;
	return 0;
}

int decode_can_0x306_Knock_Ign_Adv_Mod(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x306_ME1_7.Knock_Ign_Adv_Mod);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x306_Knock_Ign_Adv_Mod(can_obj_test_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x306_ME1_7.Knock_Ign_Adv_Mod = in;
	return 0;
}

int decode_can_0x306_Fuel_Press(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x306_ME1_7.Fuel_Press);
	rval *= 5;
	*out = rval;
	return 0;
}

int encode_can_0x306_Fuel_Press(can_obj_test_h_t *o, double in) {
	assert(o);
	in *= 0.2;
	o->can_0x306_ME1_7.Fuel_Press = in;
	return 0;
}

int decode_can_0x306_Fuel_Temp(const can_obj_test_h_t *o, uint8_t *out) {
	assert(o);
	assert(out);
	uint8_t rval = (uint8_t)(o->can_0x306_ME1_7.Fuel_Temp);
	*out = rval;
	return 0;
}

int encode_can_0x306_Fuel_Temp(can_obj_test_h_t *o, uint8_t in) {
	assert(o);
	o->can_0x306_ME1_7.Fuel_Temp = in;
	return 0;
}

int print_can_0x306_ME1_7(const can_obj_test_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "Knock_Reading = (wire: %.0f)\n", (double)(o->can_0x306_ME1_7.Knock_Reading)));
	r = print_helper(r, fprintf(output, "EGT_1 = (wire: %.0f)\n", (double)(o->can_0x306_ME1_7.EGT_1)));
	r = print_helper(r, fprintf(output, "Knock_Ign_Adv_Mod = (wire: %.0f)\n", (double)(o->can_0x306_ME1_7.Knock_Ign_Adv_Mod)));
	r = print_helper(r, fprintf(output, "Fuel_Press = (wire: %.0f)\n", (double)(o->can_0x306_ME1_7.Fuel_Press)));
	r = print_helper(r, fprintf(output, "Fuel_Temp = (wire: %.0f)\n", (double)(o->can_0x306_ME1_7.Fuel_Temp)));
	return r;
}

static int pack_can_0x307_ME1_8(can_obj_test_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* EGT_2: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16_t)(o->can_0x307_ME1_8.EGT_2)) & 0xffff;
	i |= x;
	/* GPT_1: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x307_ME1_8.GPT_1)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* GPT_2: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16_t)(o->can_0x307_ME1_8.GPT_2)) & 0xffff;
	x <<= 32; 
	i |= x;
	*data = (i);
	o->can_0x307_ME1_8_tx = 1;
	return 0;
}

static int unpack_can_0x307_ME1_8(can_obj_test_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* EGT_2: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->can_0x307_ME1_8.EGT_2 = x;
	/* GPT_1: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->can_0x307_ME1_8.GPT_1 = x;
	/* GPT_2: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->can_0x307_ME1_8.GPT_2 = x;
	o->can_0x307_ME1_8_rx = 1;
	o->can_0x307_ME1_8_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x307_EGT_2(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x307_ME1_8.EGT_2);
	rval *= 0.1;
	*out = rval;
	return 0;
}

int encode_can_0x307_EGT_2(can_obj_test_h_t *o, double in) {
	assert(o);
	in *= 10;
	o->can_0x307_ME1_8.EGT_2 = in;
	return 0;
}

int decode_can_0x307_GPT_1(const can_obj_test_h_t *o, int16_t *out) {
	assert(o);
	assert(out);
	int16_t rval = (int16_t)(o->can_0x307_ME1_8.GPT_1);
	*out = rval;
	return 0;
}

int encode_can_0x307_GPT_1(can_obj_test_h_t *o, int16_t in) {
	assert(o);
	o->can_0x307_ME1_8.GPT_1 = in;
	return 0;
}

int decode_can_0x307_GPT_2(const can_obj_test_h_t *o, int16_t *out) {
	assert(o);
	assert(out);
	int16_t rval = (int16_t)(o->can_0x307_ME1_8.GPT_2);
	*out = rval;
	return 0;
}

int encode_can_0x307_GPT_2(can_obj_test_h_t *o, int16_t in) {
	assert(o);
	o->can_0x307_ME1_8.GPT_2 = in;
	return 0;
}

int print_can_0x307_ME1_8(const can_obj_test_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "EGT_2 = (wire: %.0f)\n", (double)(o->can_0x307_ME1_8.EGT_2)));
	r = print_helper(r, fprintf(output, "GPT_1 = (wire: %.0f)\n", (double)(o->can_0x307_ME1_8.GPT_1)));
	r = print_helper(r, fprintf(output, "GPT_2 = (wire: %.0f)\n", (double)(o->can_0x307_ME1_8.GPT_2)));
	return r;
}

static int pack_can_0x340_ME1_In_1(can_obj_test_h_t *o, uint64_t *data) {
	assert(o);
	assert(data);
	register uint64_t x;
	register uint64_t i = 0;
	/* Vehicle_Speed: start-bit 0, length 16, endianess intel, scaling 0.008, offset 0 */
	x = ((uint16_t)(o->can_0x340_ME1_In_1.Vehicle_Speed)) & 0xffff;
	i |= x;
	*data = (i);
	o->can_0x340_ME1_In_1_tx = 1;
	return 0;
}

static int unpack_can_0x340_ME1_In_1(can_obj_test_h_t *o, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(dlc <= 8);
	register uint64_t x;
	register uint64_t i = (data);
	if (dlc < 8)
		return -1;
	/* Vehicle_Speed: start-bit 0, length 16, endianess intel, scaling 0.008, offset 0 */
	x = i & 0xffff;
	o->can_0x340_ME1_In_1.Vehicle_Speed = x;
	o->can_0x340_ME1_In_1_rx = 1;
	o->can_0x340_ME1_In_1_time_stamp_rx = time_stamp;
	return 0;
}

int decode_can_0x340_Vehicle_Speed(const can_obj_test_h_t *o, double *out) {
	assert(o);
	assert(out);
	double rval = (double)(o->can_0x340_ME1_In_1.Vehicle_Speed);
	rval *= 0.008;
	if (rval <= 524.28) {
		*out = rval;
		return 0;
	} else {
		*out = (double)0;
		return -1;
	}
}

int encode_can_0x340_Vehicle_Speed(can_obj_test_h_t *o, double in) {
	assert(o);
	o->can_0x340_ME1_In_1.Vehicle_Speed = 0;
	if (in > 524.28)
		return -1;
	in *= 125;
	o->can_0x340_ME1_In_1.Vehicle_Speed = in;
	return 0;
}

int print_can_0x340_ME1_In_1(const can_obj_test_h_t *o, FILE *output) {
	assert(o);
	assert(output);
	int r = 0;
	r = print_helper(r, fprintf(output, "Vehicle_Speed = (wire: %.0f)\n", (double)(o->can_0x340_ME1_In_1.Vehicle_Speed)));
	return r;
}

int unpack_message(can_obj_test_h_t *o, const unsigned long id, uint64_t data, uint8_t dlc, dbcc_time_stamp_t time_stamp) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(dlc <= 8);         /* Maximum of 8 bytes in a CAN packet */
	switch (id) {
	case 0x300: return unpack_can_0x300_ME1_1(o, data, dlc, time_stamp);
	case 0x301: return unpack_can_0x301_ME1_2(o, data, dlc, time_stamp);
	case 0x302: return unpack_can_0x302_ME1_3(o, data, dlc, time_stamp);
	case 0x303: return unpack_can_0x303_ME1_4(o, data, dlc, time_stamp);
	case 0x304: return unpack_can_0x304_ME1_5(o, data, dlc, time_stamp);
	case 0x305: return unpack_can_0x305_ME1_6(o, data, dlc, time_stamp);
	case 0x306: return unpack_can_0x306_ME1_7(o, data, dlc, time_stamp);
	case 0x307: return unpack_can_0x307_ME1_8(o, data, dlc, time_stamp);
	case 0x340: return unpack_can_0x340_ME1_In_1(o, data, dlc, time_stamp);
	default: break; 
	}
	return -1; 
}

int pack_message(can_obj_test_h_t *o, const unsigned long id, uint64_t *data) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	switch (id) {
	case 0x300: return pack_can_0x300_ME1_1(o, data);
	case 0x301: return pack_can_0x301_ME1_2(o, data);
	case 0x302: return pack_can_0x302_ME1_3(o, data);
	case 0x303: return pack_can_0x303_ME1_4(o, data);
	case 0x304: return pack_can_0x304_ME1_5(o, data);
	case 0x305: return pack_can_0x305_ME1_6(o, data);
	case 0x306: return pack_can_0x306_ME1_7(o, data);
	case 0x307: return pack_can_0x307_ME1_8(o, data);
	case 0x340: return pack_can_0x340_ME1_In_1(o, data);
	default: break; 
	}
	return -1; 
}

int print_message(const can_obj_test_h_t *o, const unsigned long id, FILE *output) {
	assert(o);
	assert(id < (1ul << 29)); /* 29-bit CAN ID is largest possible */
	assert(output);
	switch (id) {
	case 0x300: return print_can_0x300_ME1_1(o, output);
	case 0x301: return print_can_0x301_ME1_2(o, output);
	case 0x302: return print_can_0x302_ME1_3(o, output);
	case 0x303: return print_can_0x303_ME1_4(o, output);
	case 0x304: return print_can_0x304_ME1_5(o, output);
	case 0x305: return print_can_0x305_ME1_6(o, output);
	case 0x306: return print_can_0x306_ME1_7(o, output);
	case 0x307: return print_can_0x307_ME1_8(o, output);
	case 0x340: return print_can_0x340_ME1_In_1(o, output);
	default: break; 
	}
	return -1; 
}

